version: '3.8'

services:
  app:
    build: .
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    ports:
      - "22:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app